blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('post.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

if settings.DEBUG == False:
    handler404 = "accounts.views.error_404_view"
    handler500 = "accounts.views.error_500_view"

post/urls.py
from django.urls import path
from post import views

app_name='post'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.createPost, name = 'create_post'),
    path('post/<slug:slug>/', views.postDetail, name='post_detail'),
    path('post/<slug:slug>/delete/', views.postDelete, name ='post_delete'),
    path('post/<slug:slug>/update/', views.update, name ='post_update'),
    path('category/<str:category_slug>', views.category_view, name = 'post_category'),
    path('contents/', views.contents, name='content'),
    path('bookmarks/', views.bookmarks, name = 'bookmarks'),
    path('archive/', views.archive_view, name='archive'),
    path('our-team/', views.team_view, name='our-team'),
    path('privacy-policy/', views.privacy_view, name ='privacy-policy'),
    path('profile/', views.profile_view, name='profile'),
    path('terms/',views.terms_view, name='terms'),
    path('content/', views.contents),
    
]
# {% url 'app_name:url_name' %}

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from random import randint
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse
# Create your models here.



User = get_user_model()

class Profile(models.Model):

    # class PostObjects(models.Manager):
    #     def get_queryset(self):
    #         queryset = super(Post, self).get_queryset().filter(self.blogger = self.posts.author)
            
    #         return queryset
    blogger = models.OneToOneField(User, on_delete = models.CASCADE, default = 1)
    # posts = models.ForeignKey(Post, on_delete=models.CASCADE)
    # bio = models.TextField(max_length = 250)
    avatar = models.ImageField(default = '/images/profile_pics/pngfind.com-placeholder-png-6104451.png',blank = True, null = True, upload_to='images/profile_pics')

@ receiver(post_save, sender = User)
def create_user_profile(sender, instance, created,**kwargs):
    if created:
        Profile.objects.create(blogger=instance)



class Category(models.Model):
    name = models.CharField(max_length = 100, unique=True, null=True)
    category_slug = models.SlugField(max_length = 100, unique= True, blank =True, null = True)


    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.category_slug = slugify(str(self.name))
        super(Category, self).save(*args, **kwargs)

    def get_cat():
        results, _ = Category.objects.get_or_create(name='Generic')
        return results.pk
    
    def get_absolute_url(self):
        return f"/category/{self.category_slug}"
class SubCategory(models.Model):
    name = models.CharField(max_length = 100, unique=True, null=True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, blank =True, null = True)
    sub_category_slug = models.SlugField(max_length = 100, unique= True, blank =True, null = True)


    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.sub_category_slug = slugify(str(self.name))
        super(SubCategory, self).save(*args, **kwargs)

    def get_sub():
        results, _ = SubCategory.objects.get_or_create(name='generic')
        return results.pk



class Post(models.Model):
 
    choices = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.TextField(max_length=500, unique = True)
    slug = models.SlugField(max_length=200, unique=True, blank = True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    publish_on = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='post/%d/%m/%y',default =  'post/faf75719-9275-4348-b2e1-269eeb2c023b.png')
    status = models.CharField(max_length=20, choices=choices, default= 'draft')
    contents = models.TextField()
    description = models.TextField(blank = True)
    bookmarks = models.ManyToManyField(User, related_name='bookmark',default=None, blank=True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, default=Category.get_cat, blank =True, null = True)
    sub_category = models.ForeignKey(SubCategory, on_delete = models.CASCADE, default = SubCategory.get_sub, blank =True, null = True)
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ('-publish_on',)
        
    def __str__(self):
        return self.title

    
   
    def save(self, *args, **kwargs):
        mySlug = str(self.category) + str('-') + str(self.title)
        print(mySlug)
        self.slug = slugify(mySlug)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        # from django.core.urlresolvers import reverse
        return reverse('post:post_detail', kwargs={'slug': self.slug})






class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comments')
    comment = models.TextField(max_length = 10000,null=True)
    email = models.EmailField()
    publish = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length = 50)
    status = models.BooleanField(default = True)


    class Meta:
        ordering = ('publish',)

    def __str__(self):
        return f"comment by {self.name} on {self.post}"

class Bookmarks(models.Model):
    pass

post/forms.py
from django.forms import ModelForm
from django import forms
from post.models import Post, Comment, Profile, Category
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django_summernote.fields import SummernoteTextField



class PostForm(forms.ModelForm):
    # # contents = SummernoteTextField()
    # # model = Post
    contents = forms.CharField(widget=SummernoteWidget())

    
    class Meta:
        model = Post
        fields = ['title', 'status', 'description','category','image','tags','contents']
        widgets = {
        "title": forms.Textarea(
        attrs={'style':'resize:none; padding:0.7rem;','class': 'meta','placeholder':'Enter your title here'}
        ),
    
        'tags': forms.Textarea(
            attrs={ 'style':'resize:none; padding:0.7rem;','class': 'meta','placeholder':'Enter your tags here'}
        ),
        # # category= forms.ModelChoiceField(queryset=Category.objects.all() )
        # # # status = forms.CharField(widget=forms.Select(choices=Post.choices))

        "description": forms.Textarea(
            attrs={'style':'resize:none; padding:0.7rem;','class': 'meta','placeholder':'Enter your post description here'}
        ),
# <input type="file" name="image" accept="image/*" id="id_image">
        # "image": forms.ImageField(
            # attrs={''}
        # )
        }



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email','comment')
        # widgets = {
        #     'comment': forms.Textarea(
        #         attrs={'placeholder':"Add a comment.." ,'style':"resize: none;", 'rows':"4", 'cols':"50", "name":"comment", 'form':"usrform" }
        #     )
        # }


class ProfileForm(forms.ModelForm):
    class Meta:
        fields = ('avatar',)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Category
from .forms import PostForm,CommentForm
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
# Create your views here.
# list view for home page
def index(request):
    # retrieve all posts and order them by their publish date 
    posts = Post.objects.filter(status='published').order_by('-publish_on')
    common_tags = Post.tags.most_common()[:4]

    context = {
        'posts': posts,
        'common_tags': common_tags
    }
    return render(request, 'post/index.html', context)
    # return render(request, 'post/index_john.html', context)
    # return render(request, 'post/content-page.html', context)


# create a post
def createPost(request):
    if request.user.is_authenticated:
        form = PostForm
        if request.method == 'POST':
            form = PostForm(request.POST,request.FILES)
            
            if form.is_valid():
                myform = form.save(commit =False)
                myform.author = request.user
                myform.save()
                form.save_m2m()
                return redirect('post:index')
            else: 
                form = PostForm
    else:
        return redirect('login')
    
    context = {'form': form}

    return render(request, 'post/create.html', context)


# specific posts
def postDetail(request, slug):
    post = get_object_or_404(Post, slug=slug, status = 'published')
    
    comments = post.comments.filter(status = True)
    user_comment = None
    commentForm = CommentForm()
    if request.method == 'POST':
        commentForm = CommentForm(request.POST)
        if commentForm.is_valid():
            user_comment = commentForm.save(commit =False)
            user_comment.post = post
            user_comment.save()
    
            return redirect('post:post_detail', post.slug)
        else:
            commentForm = CommentForm()
    context = {
        'post': post,
        'commentForm': commentForm,
        'user_comments': user_comment,
        'comments': comments
    }
    return render(request, 'post/detail.html', context)

def category_view(request, category_slug):
    category = Category.objects.get(category_slug=category_slug)
    post_by_category = Post.objects.filter(category=category, status= 'published')
    return render(request, 'post/category.html', {'posts':post_by_category})

# this is supposed to be for only bloggers but might just redo it
def bloggerDetail(request, slug):
    pass


# deleting posts
def postDelete(request, slug):
    post = get_object_or_404(Post, slug=slug)

    blogger = post.author

    if request.method == 'POST' and request.user.is_authenticated and (request.user == blogger or request.user.is_staff):
        post.delete()
        messages.success(request, 'Post has being successfully deleted! ')
        return redirect('post:index')

    context = {
        'post':post,
        'blogger':blogger,
    }
    return render(request, 'post/delete.html', context)


# updating posts
def update(request, slug):
    post = Post.objects.get(slug = slug)
    form = PostForm(instance  = post)
    if request.method  == 'POST':
        form = PostForm(request.POST,request.FILES, instance = post)
        if form.is_valid():
            myform = form.save(commit =False)
            myform.author = request.user
            myform.save()
            form.save_m2m()
            return redirect('post:post_detail', post.slug)
    context = {'form':form}
    return render(request, 'post/update.html', context)


# class CategoryListView(ListView):
#     template_name = 'post/category.html'
#     context_object_name = 'category_list'

#     def get_queryset(self):
#         content = {
#             'categories': self.kwargs['category'],
#             'posts': Post.objects.filter(category__name = self.kwargs['category']).filter(status='published')
#         }
#         return content 


@ login_required
def bookmarks(request):
    # new = Post.objects.filter(bookmarks=request.user)
    return render(request,
                  'post/bookmarks.html',
                  {})

def contents(request):
    posts = Post.objects.filter(author = request.user).order_by('-publish_on')
    # common_tags = Post.tags.most_common()[:4]

    context = {
        'posts': posts,
        # 'common_tags': common_tags
    }
    
    return render(request, 'post/content-page.html', context)

def archive_view(request):


    return render(request, 'raw/archive.html')

def team_view(request):

    return render(request, 'raw/ourteam.html')

def privacy_view(request):

    return render(request, 'raw/privavypolicy.html')

def profile_view(request):

    return render(request, 'raw/profilepage.html')



def terms_view(request):

    return render(request, 'raw/termsofservice.html')


def funcname(request):
    pass
   

templates/post/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {{category_list.categories}} <br>
    {% for post in posts %}
    <br>
    <a href="{% url 'post:post_detail' post.slug %}">{{post.title}}</a><br>
    <a href="{{ post.image.url }}">
            <img src="{{ post.image.url }}" alt="Lights" style="height:20%;width:20%">
         </a><br>
        {{post.contents |safe| truncatechars:500 }}<br>
    {% endfor %}
</body>
</html>

templates/post/content-page.html
{% load static %}
<!DOCTYPE html>


    <!--  -->
    <!-- HEADER & MOBILE MENU END-->
{% include 'post/nav.html' %}

    <main>
     <section class="first-container">
        <p>Hello</p>
        <h3>{{request.user}}</h3>
        <div class="first-container-links">
            <a href="">MY SETTINGS</a>
            <a href=""> MY BOOKMARKS (0)</a>
            <a href="" class="active"> &nbsp; &nbsp; &nbsp; &nbsp; MY CONTENT (20) &nbsp; &nbsp; &nbsp; &nbsp;</a>
        </div>
        <hr class="hr-top">
     </section>

     <section class="second-container">
        <div class="second-container-content">
            <div class="content1">
              <h3>My Content</h3>
            </div>
          </div>
            <div class="content2">
              <p>20 post</p>
            </div>
        </div>
        <div class="content3">
           FILTER BY: &nbsp; &nbsp;  <select class="select">
                <option disabledselect>ALL</option>
                <option>DRAFT</option>
                <option>PUBLISHED</option>
            </select>
        </div>
            </section>

            
     

     <section class="main-content-container">
      <!-- LEFT SECTION STARTS CONTENT 1-->

      <div>
        <div class="right-header">
          <h3></h3><div>

          </div>

          <!--This is the Div that carries the left section content-->
        </div>
      </div>

     <!-- MIDDLE SECTION STARTS CONTENT 1-->
     {% for post in posts %}
     <!-- <div>
         {% for tag in post.tags.all %}
         tags: #{{tag}} 
         {% endfor %}
         title: {{post.title}} <br>, 
         category: {{post.category}},<br> 
         author: {{post.author.get_full_name}} <br>
         {{post.description}}
          <a href="{% url 'post:post_detail' post.slug %}">
                 <img src="{{ post.image.url }}" alt="Lights" style="height:20%;width:20%">
                 
                   
                 
               </a>
         <a href="{% url 'post:post_detail' post.slug %}">full post</a>
      {% if user.is_authenticated %}
      <a href="{% url 'post:post_update' post.slug %}">update post</a>
      <a href="{% url 'post:post_delete' post.slug %}">delete post</a>
      {% endif %}
       </div> -->
      
      <div>

      <div  class="middle-container">
      <div class="middle-section">
       <div class="middle-image">
         <!-- <a href=""><img src="{% static "./img/King-of-thieves.svg" %}" alt="lord-of-rings-img"></a> -->
         <a href="{% url 'post:post_detail' post.slug %}">
          <img src="{{ post.image.url }}" alt="Lights" >
          </a>
          <!-- style="height:20%;width:20%" -->
        </div>
       <div class="middle-content">
         <a href="">Review: {{post.title}}</a>
             <p>{{post.description}} </p>
              <div class="status-section" id="status1">
                <p class="status-text">STATUS</p>
                 <p class="published-text">{{post.status}}
                  <i class="fa-solid fa-angle-down"></i></p>
               </div>

               <div class="status-section2" id="icon-right1">
                <p class="edit-icon"><i class="bi bi-pencil"></i>&nbsp; <a href="{% url 'post:post_update' post.slug %}">Edit</a></p>
                <p class="delete-icon"><i class="fa-regular fa-trash-can"></i>&nbsp; <a href="{% url 'post:post_delete' post.slug %}">Delete</a></p>
               </div>
       </div>
         <hr class="hr-line"/>
      </div>
      {% endfor %}
      <!-- MIDDLE SECTION STARTS CONTENT 2-->

      <!-- <div class="middle-section">
         <div class="middle-image">
           <a href=""><img src="{% static './img/lord-of-rings-img.svg' %}" alt="lord-of-rings-img"></a>
         </div>
         <div class="middle-content">
           <a href="">The Lord of the Rings: The Rings of Power recap: Not all who wander are lost</a>
               <p>Welcome back to Middle-earth, where people love to burst out into song
                 — especially when they're traversing wild nature. </p>
                 <div class="status-section" id="status2">
                  <p class="status-text">STATUS</p>
                   <p class="published-text">PUBLISHED
                    <i class="fa-solid fa-angle-down"></i></p>
                 </div>
                 <div class="status-section2" id="icon-right2">
                  <p class="edit-icon"><i class="bi bi-pencil"></i>&nbsp; Edit</p>
                  <p class="delete-icon"><i class="fa-regular fa-trash-can"></i>&nbsp; Delete</p>
                 </div>
         </div>
           <hr class="hr-line"/>
        </div>

      MIDDLE SECTION STARTS CONTENT 3

      <div class="middle-section">
         <div class="middle-image">
           <a href=""><img src="{% static 'img/Ayinla-review.svg' %}" alt="lord-of-rings-img"></a>
         </div>
         <div class="middle-content">
           <a href="">'Ayinla' Review: Tunde Kelani's Movie Worth The Hype Thanks To Adedimeji Lateef's Singular Performanced</a>
               <p>Ayinla is a film that tells the story of Nigerian musician, Ayinla Omowura, who used Apala music to address issues of the contemporary society
                 - commending and criticizing various governmental and individual acts. </p>
                <div class="status-section" id="status3">
                  <p class="status-text">STATUS</p>
                   <p class="published-text">PUBLISHED
                    <i class="fa-solid fa-angle-down"></i></p>
                 </div>
                 <div class="status-section2" id="icon-right3">
                  <p class="edit-icon"><i class="bi bi-pencil"></i>&nbsp; Edit</p>
                  <p class="delete-icon"><i class="fa-regular fa-trash-can"></i>&nbsp; Delete</p>
                 </div>
         </div>
           <hr class="hr-line"/>
        </div>

        <!-- MIDDLE SECTION STARTS CONTENT 4

      <div class="middle-section">
        <div class="middle-image">
          <a href=""><img src="{% static 'img/Asake.svg' %}" alt="lord-of-rings-img"></a>
        </div>
        <div class="middle-content">
          <a href="">Asake Sets A New Billboard Record</a>
              <p>Asake is the rave of the moment! The music star is
                trending once again following a recent achievement. </p>
                <div class="middle-icon-section">
               <div class="status-section" id="status4">
                 <p class="status-text">STATUS</p>
                  <p class="published-text">PUBLISHED
                   <i class="fa-solid fa-angle-down"></i></p>
                </div>
                <div class="status-section2" id="icon-right4">
                  <p class="edit-icon"><i class="bi bi-pencil"></i>&nbsp; Edit</p>
                  <p class="delete-icon"><i class="fa-regular fa-trash-can"></i>&nbsp; Delete</p>
                 </div>
                </div>
        </div>
       </div>


      </div>
    </div> -->
      <!--This is the Div that carries/ends the middle section content-->
  </div>

  <!-- RIGHT SECTION STARTS CONTENT 1-->

  <div>
    <div class="right-header">
      <h3></h3><div>

      </div>

      <!--This is the Div that carries the right section content-->
               </div>
    </section>


<section class="page-num">
  <hr class="hr-page-num"/>
  <div class="page-num-content">
     <a href="#" class="page-btn start-page"><img src="{% static './img/less-than.svg' %}" alt=""></a>
     <a href="#" class="page-btn active">1</a>
     <a href="#" class="page-btn prev-page">2</a>
     <a href="#" class="page-btn">3</a>
     <a href="" class="page-btn">4</a>
     <a href="" class="page-btn">5</a>
     <a href="" class="page-btn end-page"><img src="{% static './img/Greater-than.svg' %}" alt=""></a>
  </div>
</section>

<section>
  <div class="last-header-content">
    <h3> WRITER'S PICK</h3>
    <p> SEE ALL</p>
  </div>
  <hr class="hr-bottom">
</section>

<section class="last-container">
  <!--Parent div starts-->
  <div class="writers-content-container">

     <div class="writers-content">
    <img src="{% static './img/Constance1.svg' %}" alt="Constance1">
    <p class="para1">Constance Wu Says Chris Pratt Was 'So Supportive' as
      She Returned to Work After Giving Birth</p>
    <div class="post-by">
      <p class="post-by-bolder">By Amara</p>
      <p>September 23, 2022  12:32</p>
    </div>
     </div>

     <div class="writers-content">
      <img src="{% static './img/Contance2.svg' %}" alt="Constance2">
    <p class="para1">Constance Wu Talks About Her Baby Girl's 'Little Blue Butt': 'It's Very Special'</p>
    <div class="post-by">
      <p class="post-by-bolder" id="post-date">By Amara</p>
      <p id="post-date">September 23, 2022  12:32</p>
    </div>

     </div>
     <div class="writers-content">
      <img src="{% static './img/Constance3.svg' %}" alt="Constance3">
      <p class="para1">Constance Wu Says She Attempted Suicide After
        'Fresh Off the Boat' Twitter Drama: 'Almost Lost My Life'</p>
      <div class="post-by">
        <p class="post-by-bolder">By Amara</p>
        <p>September 23, 2022  12:32</p>
      </div>

     </div>
  </div>
</section>
<section>
  <hr>
</section>


<section class="newsletter" id="subscribe">
  <h2>STAY UPDATED</h2>

  <p>
    Get the latest creative news from Blogga about Art , Fashion,
    Entertainment and lots more.
  </p>

  <form action="#">
    <input
      type="email"
      name="email"
      id="email"
      placeholder="Your Email Address"
    />
    <button type="submit" class="subscribe button">Subscribe</button>
  </form>
</section>
<!--  -->
<!-- SUBSCRIBE SECTION END-->

<section class="icon">
  <a href="" class="gototop"> <i class="far fa-edit"></i>
  </a>
</section>


    </main>
    <!-- FOOTER START-->
    <!--  -->
    {% include "post/footer.html" %}    <!--  -->
    <!-- FOOTER END-->
    <script src="{% static './js/index.js' %}"></script>

  </body>
</html>

templates/post/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if request.user.is_authenticated and request.user == blogger or request.user.is_staff %}
    <h1>Delete {{post.title}} ?</h1>
    <form action="" method="post">
        {% csrf_token %}
        ARE YOU SURE????
        <input type="submit" value="Yes"/>
        <a href="{% url 'post:index' %}">Cancel </a>
    </form>
{% endif %}

    
</body>
</html>

templates/post/footer.html
{% load static %}
<!DOCTYPE html>
<footer class="main_footer">
    <div class="footer_top">
      <img src="{% static './img/logo_resources/Favicon_White.png' %}" alt="Blogga Icon" />
      <ul>
        <li><a href="#">ADVERTISE</a></li>
        <li><a href="./write-for-us.html">WRITE FOR US</a></li>
        <li><a href="./category-page.html">CATEGORIES</a></li>
        <li>
          <a href="./index.html"
            ><img
              src="{% static './img/logo_resources/Favicon_White.png' %}"
              alt="Blogga Icon"
          /></a>
        </li>
        <li><a href="./archive.html">ARCHIVES</a></li>
        <li><a href="./termsofservice.html">TERMS OF SERVICE</a></li>
        <li><a href="./privacypolicy.html">PRIVACY</a></li>
      </ul>
    </div>

    <div class="footer_middle">
      <a href="#">
        <i class="fa-brands fa-facebook"></i>&ThinSpace;
        <span>FACEBOOK</span> </a
      ><a href="#"
        ><i class="fa-brands fa-twitter"></i>&ThinSpace;
        <span>TWITTER</span> </a
      ><a href="#"
        ><i class="fa-brands fa-linkedin-in"></i>&ThinSpace;
        <span>LINKEDIN</span> </a
      ><a href="#"
        ><i class="fa-brands fa-youtube"></i>&ThinSpace;
        <span>YOUTUBE</span></a
      ><a href="#"
        ><i class="fa-brands fa-instagram"></i>&ThinSpace;
        <span>INSTAGRAM</span> </a
      ><a href="#"
        ><i class="fa-brands fa-pinterest"></i>&ThinSpace;
        <span>PINTEREST</span>
      </a>
    </div>

    <div class="footer_bottom">
      <p>© 2022 The Blogga Team All Rights Reserved</p>
      <a href="#">Site Map</a>
    </div>
  </footer>

templates/post/index_john.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
</head>
<body>
    <div>
            {{request.user}} <br><br><br><br><br>
    {% for post in posts %}
    <div>
        {% for tag in post.tags.all %}
        tags: #{{tag}} 
        {% endfor %}
        title: {{post.title}} <br>, 
        category: {{post.category}},<br> 
        author: {{post.author.get_full_name}} <br>
        {{post.description}}
        <a href="{% url 'post:post_detail' post.slug %}">
                <img src="{{ post.image.url }}" alt="Lights" style="height:20%;width:20%">
                
                  
                
              </a>
        <a href="{% url 'post:post_detail' post.slug %}">full post</a>
     {% if user.is_authenticated %}
     <a href="{% url 'post:post_update' post.slug %}">update post</a>
     <a href="{% url 'post:post_delete' post.slug %}">delete post</a>
     {% endif %}
      </div>
     {% endfor %}
     
    </div> <br><br><br>
</body>
</html>

templates/post/login_modal.html
{% load static %}
<div class="login-modal">
    <section class="login-body">
      <img
        src="{% static './img/Login/mobile_blob1.png'%}"
        alt="mobile blob design"
        class="mobile_blob1"
      />
      <img
        src="{% static './img/Login/mobile_blob2.png'%}"
        alt="mobile blob design"
        class="mobile_blob2"
      />
      <img
        src="{% static './img/Login/mobile_blob3.png'%}"
        alt="mobile blob design"
        class="mobile_blob3"
      />

      <main class="login-main">
        <div class="left-div">
          <img
            src="{% static './img/Login/login_top_blob.png'%}"
            alt="blob design "
            class="top_blob"
          />
          <img
            src="{% static './img/Login/login_main_image.png'%}"
            alt="welcome image"
          />
          <img
            src="{% static './img/Login/login_bottom_blob.png'%}"
            alt="blob design "
            class="btm_blob"
          />
        </div>

        <div class="right-div">
          <i
            class="fa-solid fa-xmark login-modal-close"
            onclick="hideLoginModal()"
          ></i>
          <div class="right-div-container">
            <h3 class="head-txt">Welcome Back : )</h3>
            <!-- form starts here -->
            <form method="post">
                {% csrf_token %}

            <input
              type="text"
              placeholder="Username"
              id="login-username"
             
              required
            />

            <br />
          
            <div class="password-eye">
              <input
                type="password"
                placeholder="********"
             
                id="login-password"
                required
              />
              <i class="bi bi-eye" onclick="passwordToggle()"></i>
              <i class="bi bi-eye-slash" onclick="passwordToggle()"></i>
            </div>

            <a href="{%url 'password_reset'%}" class="forgot-password"
              > Forgot Password?</a
            > 
            <!-- <br /> -->

            <label for="remember-me" class="remem-label">
              <input
                type="checkbox"
                name="remember-me"
                id="remember-me"
              />&nbsp; <small>Remember Me</small></label
            >
            <br />
            {% if messages %}
            {% for message in messages %}
            {% if message.tags %}<div class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
            {% endif %}
            <button type="submit" class="login-button">Log In</button>
            <!-- end form -->
          </form>
            <div class="or-separator">
              <hr />
              <p>OR</p>
              <hr />
            </div>

            <button type="button" class="continue-button">
              <img
                src="{% static './img/google.png'%}"
                alt=""
                class="google"
              />
              &nbsp; Continue With Google
            </button>

            <p class="base-txt">
              Become a Blogga?
              <a href="{% url 'signup' %}" class="signup-link">
                Write For Us</a
              >
            </p>
          </div>
        </div>
      </main>
    </section>
  </div>